<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Version>2026.7.24</Version>
        <Authors>Theodoros Bebekis</Authors>
        <Product>Deltos</Product>
        <Copyright>Copyright (c) 2026 Theodoros Bebekis</Copyright>
        <ApplicationIcon>Assets\Deltos.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
        <PackageReference Include="Avalonia" Version="12.0.4" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.18">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Markdig" Version="1.3.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Tripous.Avalon\Tripous\Tripous.csproj" />
        <ProjectReference Include="..\..\Tripous.Avalon\Tripous.Desktop\Tripous.Desktop.csproj" />
        <ProjectReference Include="..\..\Tripous.Avalon\Tripous.Logging\Tripous.Logging.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Include="Assets\**" />
      <EmbeddedResource Include="Resources\Documentation\*.*" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Resources\Wiki\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
